--- # Add users with a list
- name: Add users
  hosts: all
  become: true
  become_method: sudo
  tasks:
  - name: Information
    ansible.builtin.debug:
      var: ansible_facts['distribution']
  - name: Create user accounts
    ansible.builtin.user:
      name: "{{ item }}"
      state: present
      generate_ssh_key: yes
    with_items:
    - bob
    - lisa
    - ben
    - katy
     
