---
- name: Write a playbook to install ‘zlib’ and ‘vim’ if the file ‘/tmp/mario’ exists on the system.
  hosts: all
  become: yes
  become_method: sudo
  vars:
    mario_file: /tmp/mario
    package_list:
        - 'zlib' 
        - 'vim'
  tasks:
    - name: Check for mario file
      stat:
          path: "{{ mario_file }}"
      register: mario_f

    - name: Install zlib and vim if mario file exists
      become: "yes"
      package:
          name: "{{ item }}"
          state: present
      with_items: "{{ package_list }}"
      when: mario_f.stat.exists

#***************** Another Example *****************
  - name: Get stats of a file
    ansible.builtin.stat:
      path: /etc/foo.conf
    register: st

  - name: Fail if the file does not belong to 'root'
    ansible.builtin.fail:
      msg: "Whoops! file ownership has changed"
    when: st.stat.pw_name != 'root'

# Determine if a path exists and is a directory.  Note that we need to test
# both that p.stat.isdir actually exists, and also that it's set to true.
  - name: Get stats of the FS object
    ansible.builtin.stat:
      path: /path/to/something
    register: p
  - name: Print a debug message
    ansible.builtin.debug:
      msg: "Path exists and is a directory"
    when: p.stat.isdir is defined and p.stat.isdir

...
