---
- name: Testing a simple variablle
  hosts: all
  become: true
  become_method: sudo
  vars:
    user: lisa 
  tasks:
    - name: create a user {{ user }}
      ansible.builtin.user:
        name: "{{ user }}"

...