---
- name: Simple loop instead of with_items
  hosts: all
  become: true
  become_method: sudo
  vars:
    my_services:
    - crond
    - sshd
  tasks:
  - name: Testing a simple loop
    service: 
      name: "{{ item }}"
      state: present
    loop: "{{ my_services }}"
...    
